### ISSUE TITLE
Add "getting started" instructions

### ISSUE THREAD

**Issue by UksusoFF** [kaido24/btgrid#1]
Please add some instructions for install this plugin.

I've try add this strings to my ckeditor config:
config.extraPlugins = 'widget,dialog,btgrid';
and 'btgrid' to toolbar.
But button isn't displayed.

PS: CKEditor cersion: 4.5.1

**Comment by kaido24** [comment]
I guess you forgot to add it to config.toolbarGroups, as one of the items.

My config.js file contents.
/**
- @license Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
- For licensing, see LICENSE.md or http://ckeditor.com/license
  */

CKEDITOR.editorConfig = function( config ) {
    // Define changes to default configuration here.
    // For complete reference see:
    // http://docs.ckeditor.com/#!/api/CKEDITOR.config

```
// The toolbar groups arrangement, optimized for two toolbar rows.
config.toolbarGroups = [
    { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
    { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
    { name: 'links' },
    { name: 'insert' },
    { name: 'forms' },
    { name: 'tools' },
    { name: 'document',    groups: [ 'mode', 'document', 'doctools' ] },
    { name: 'others' },
    '/',
    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
    { name: 'paragraph',   groups: ['btgrid', 'list', 'indent', 'blocks', 'align', 'bidi' ] },
    { name: 'styles' },
    { name: 'colors' },
    { name: 'about' }
];
config.extraPlugins = 'widget,dialog,btgrid';

// Remove some buttons provided by the standard plugins, which are
// not needed in the Standard(s) toolbar.
config.removeButtons = 'Underline,Subscript,Superscript';

// Set the most common block elements.
config.format_tags = 'p;h1;h2;h3;pre';

// Simplify the dialog windows.
config.removeDialogTabs = 'image:advanced;link:advanced';
```

};

**Comment by UksusoFF** [comment]
No, I did it:

> I've try add this strings to my ckeditor config:
> config.extraPlugins = 'widget,dialog,btgrid';
> and 'btgrid' to toolbar.

Also I have worked other plugins, for eg:
http://ckeditor.com/addon/layoutmanager

**Comment by kaido24** [comment]
I guess there is could be something related with widget plugin requirements. I used build my editor option and it worked. Also noticed now there where no need to add widget and dialog for me. Also noticed there are two new plugins to add if you do it this way. http://ckeditor.com/addon/lineutils

**Comment by UksusoFF** [comment]
Lineutils already loaded via builded package: http://ckeditor.com/builder
Layout Manager also uses widget and their requirements. And it's work now for me.

**Comment by kaido24** [comment]
Looks like you are right. This plugin is unusable with CK 4.5 at this moment. I will work on fixing that.

**Comment by kaido24** [comment]
Now it works with currently stable release.

**Comment by UksusoFF** [comment]
Thanks, it's works.
