### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by benr77** [kaido24/btgrid#14]
Hi. Great work here - thanks. Any chance you could tag a release so it's easier to use a stable commit?

Also via Bower I get `Package cke-btgrid not found` - have you registered the Bower name?

**Comment by kaido24** [comment]
Did the tagging. Will look into bower..

**Comment by Perni1984** [comment]
@kaido24: Unfortunately I still cannot find the package in the official bower registry.

You can register it with `bower register <my-package-name> <git-endpoint>`, 
see [Bower - Creating Packages](https://bower.io/docs/creating-packages/#register)

**Comment by kaido24** [comment]
Got it now :)
