### ISSUE TITLE
Would It be difficult to port it to Reflex? (flexbox library)

### ISSUE THREAD

**Issue by FerchoCarcho** [kaido24/btgrid#16]
Hello @kaido24 , I wanna ask you if this great plugin you have made would be possible to be translated to [Reflex.](http://leejordan.github.io/reflex/docs/index.html)
You know nowdays Flexbox has done life very easy when you want to mix text with images. or arrange the space in a  more efficient way.
Reflex is very similar to Bootstrap, it just uses flexbox.
Could you comment on this please?

Thank you once again.

**Comment by FerchoCarcho** [comment]
It was just change the markup on the Plugin and at the css file. Thank you very much.

**Comment by kaido24** [comment]
Good :) Did you create  a branch or something for others to use?

**Comment by FerchoCarcho** [comment]
I could Copy the sensitive data here. I dont know how to do the branch thing. can you?
