### ISSUE TITLE
Icon not showing in toolbar

### ISSUE THREAD

**Issue by regileeso** [kaido24/btgrid#17]
Obviously the plugin is loaded, but the icon is not showing in toolbar.
I really have no clue why it's like that. Maybe this is because get-simple CMS includes ckeditor?

CKEditor version:"4.5.9"

My config: 

`config.toolbar_advanced = 
        [['Bold', 'Italic', 'Underline', 'NumberedList', 'BulletedList', 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'Table', 'TextColor', 'BGColor', 'Link', 'Unlink', 'Image', 'RemoveFormat', 'Source'],
        '/',
        ['Styles','Format','Font','FontSize','btgrid','Youtube','Maximize']];`

```
config.toolbar_basic = 
    [['Bold', 'Italic', 'Underline', 'NumberedList', 'BulletedList', 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'Link', 'Unlink', 'Image', 'RemoveFormat', 'Source']];

/*
 * Add 'about' button for debug
 */
// config.toolbar_advanced.push(Array("About"));
// config.toolbar_basic.push(Array("About"));

var extraPlugins = new Array();
extraPlugins.push('widget');
extraPlugins.push('dialog');
extraPlugins.push('btgrid');
extraPlugins.push('autogrow');         // auto grow ckeditor height on content
extraPlugins.push('codesnippet');      // enables code insertion, 'CodeSnippet'
extraPlugins.push('youtube');
extraPlugins.push('maximize');
```

Firebug shows me that CSS and other stuff has been loaded. Please see this screenshot. https://picload.org/image/rdowpccg/btgrid.png

Also there's not JS error at all, the editor works normal.

Can someone tell me how to get the icon shown in the toolbar?

**Comment by kaido24** [comment]
I would suggest to try this one https://www.drupal.org/node/2407721#comment-10367869

**Comment by regileeso** [comment]
This worked out! Thanks.

Add this to plugin.js, after editor.widgets.add();

`// Register the toolbar buttons for the CKEditor editor instance.
editor.ui.addButton('btgrid',
{
  label : 'Insert Bootstrap 3 Grid',
  icon : this.path + 'icons/btgrid.png',
  command : 'btgrid'
});`
