### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by HartLarsson** [kaido24/btgrid#18]
I still testing you plugins and works nice for me.
I've noticed a cosmetic problem on the icon. Is not really grayscale/bw but is for me a kinda of violet color
![image](https://cloud.githubusercontent.com/assets/16102074/20431582/1a076d7c-ad9b-11e6-8b57-1819e5f5c0ff.png)

is possible to change the icon or rebuild with same style of othe ck icons (not colored)

Ty in advance

**Comment by kaido24** [comment]
Hei, that's by design inspired by bootstrap 3 colors :) You may replace it with your own button design. If you look into ckeditor themes then you may see different color schemes. http://ckeditor.com/addons/skins/all

**Comment by HartLarsson** [comment]
thank you for the answer. I've already took alook to the other styles/theme :)
Anyway i will keep the color... has sense now :) i thought was a sort of desaturation problem :)
