### ISSUE TITLE
Duplicates when press "undo" button

### ISSUE THREAD

**Issue by maykelesser** [kaido24/btgrid#4]
Hello!
Just a correction suggestion:
Using the btgrid: if I create (eg: 2 columns and 1 row), writing something in any column and press the "Undo" button, the row is duplicated incorrectly, missing some HTML code.

Tested on 4.4.7 version.

**Comment by UksusoFF** [comment]
Same issue with source switching.

You can see this on video: https://yadi.sk/i/tjAtAJ5Hk2iPx

**Comment by kaido24** [comment]
Now its fixed

**Comment by UksusoFF** [comment]
Issue with "Source" still here.

**Comment by kaido24** [comment]
Try hard reload when using chrome browser  (it will be an option after inspector is  active) with Drupal + clear cache after that since it might make your drupal work strange way. Let me know the results with new video if it didn't work for you. You should also see new css styles implementation.

**Comment by UksusoFF** [comment]
After clear cache and update CKEditor to latest version (4.5.4) i'm again can't get it on panel. :(

**Comment by kaido24** [comment]
Do you use CKEditor module?

**Comment by UksusoFF** [comment]
Yes, and styles and js injected on page:

![default](https://cloud.githubusercontent.com/assets/1931442/11043668/4f5e7e38-8737-11e5-94a9-7bc7e373b3be.png)

![default](https://cloud.githubusercontent.com/assets/1931442/11043696/77af865c-8737-11e5-95fd-caea4f56f8bb.png)

**Comment by UksusoFF** [comment]
I've revert back to this commit and button is showing: https://github.com/kaido24/btgrid/commit/6eb67dcfea2dd07b33e8d70203cafd798fe41ba7

**Comment by kaido24** [comment]
Yes I see. DId the same change for myself at Drupal installation. Will work
on that later. This is not as it has to be for this widget. There will be
duplicate icons if I add this to vanilla CKeditor test. You may look into
tutorial at CKEditor site.
http://docs.ckeditor.com/#!/guide/widget_sdk_tutorial_1

2015-11-09 21:31 GMT+02:00 Kirill Uksusov notifications@github.com:

> I've revert back to this commit and button is showing:
> 6eb67dc
> https://github.com/kaido24/btgrid/commit/6eb67dcfea2dd07b33e8d70203cafd798fe41ba7
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kaido24/btgrid/issues/4#issuecomment-155166620.

## 

Lugupidamisega, Kaido Toomingas
Best 4U OÜ
Veebis: www.web3.ee

**Comment by kaido24** [comment]
Looks like now it's  working at both systems.

2015-11-09 22:36 GMT+02:00 Kaido Toomingas toomingas.k@gmail.com:

> Yes I see. DId the same change for myself at Drupal installation. Will
> work on that later. This is not as it has to be for this widget. There will
> be duplicate icons if I add this to vanilla CKeditor test. You may look
> into tutorial at CKEditor site.
> http://docs.ckeditor.com/#!/guide/widget_sdk_tutorial_1
> 
> 2015-11-09 21:31 GMT+02:00 Kirill Uksusov notifications@github.com:
> 
> > I've revert back to this commit and button is showing:
> > 6eb67dc
> > https://github.com/kaido24/btgrid/commit/6eb67dcfea2dd07b33e8d70203cafd798fe41ba7
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kaido24/btgrid/issues/4#issuecomment-155166620.
> 
> ## 
> 
> Lugupidamisega, Kaido Toomingas
> Best 4U OÜ
> Veebis: www.web3.ee

## 

Lugupidamisega, Kaido Toomingas
Best 4U OÜ
Veebis: www.web3.ee

**Comment by UksusoFF** [comment]
Yes, now it's work. Thanks.
